services:
  - type: web
    name: flask-ddos-server
    runtime: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server.app:app -k gevent -w 1 -b 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
